name: build 

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  default-nix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: amazonka
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix-build default.nix -A library -A checks -A exes -A shell

  generate-nix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: amazonka
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix-build generate.nix --arg audit true --arg format false
