name: build 

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  core:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, ghc: ghc8102 }
          - { os: ubuntu-latest, ghc: ghc884 }
          - { os: macos-latest, ghc: ghc8102 }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: amazonka
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix-build -A workflow.core --argstr ghcVersion ${{ matrix.ghc }}

  libs:
    needs:
      - core
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, ghc: ghc8102 }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: amazonka
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix-build -A workflow.libs --argstr ghcVersion ${{ matrix.ghc }}
